language: ruby
arch:
  - amd64
  - arm64
os:
  - linux
  # - osx
before_install:
  - gem install bundler -v 1.10.6
  - bundle install
rvm:
  - 3.2.0
  - 3.1.0
  - 2.7.1
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - 2.2.2
notifications:
  email: false
sudo: required
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
script:
  - echo CFLAGS = $CFLAGS
  - echo cflags = $cflags
  - bundle exec rake install
  - env VERBOSE=1 bundle exec rspec --format documentation
